[workspace]

members = [
    "heliosphere",
    "heliosphere-core",
    "heliosphere-signer",
]

[workspace.dependencies]
heliosphere-core = { path = "./heliosphere-core" }
heliosphere-signer = { path = "./heliosphere-signer" }
